# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += nsView.cpp
CPPSRCS += nsViewManager.cpp
MOZBUILD_CXXFLAGS += -Id:/Projects/DanknetExplorer/dne2/obj-i686-pc-mingw32/dist/include/cairo
RTL_FLAGS += -MD
LIBRARY_NAME := view
FORCE_STATIC_LIB := 1
REAL_LIBRARY := view.lib
DEFINES += -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
