# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DAPP_VERSION=52.9.2022.06.24 -DMOZ_APP_NAME=danknet_explorer -DMOZ_APP_DISPLAYNAME=Danknet_Explorer -DMOZILLA_VERSION=4.8.3
DIST_SUBDIR = browser
FINAL_TARGET = $(if $(XPI_NAME),$(DIST)/xpi-stage/$(XPI_NAME),$(DIST)/bin)$(DIST_SUBDIR:%=/%)
RTL_FLAGS += -MD
