# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += OggCodecState.cpp
CPPSRCS += OggCodecStore.cpp
CPPSRCS += OggDecoder.cpp
CPPSRCS += OggDemuxer.cpp
CPPSRCS += OggWriter.cpp
CPPSRCS += OpusParser.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := dom_media_ogg
FORCE_STATIC_LIB := 1
REAL_LIBRARY := dom_media_ogg.lib
DEFINES += -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
